modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="arkimedian"
version="0.0.1"
displayName="Project Arkimedian"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Blackstone Studio"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.arkimedian]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.arkimedian]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration