
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.arkimedian.init;

import org.lwjgl.system.windows.INPUT;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.arkimedian.item.WrenchItem;
import net.mcreator.arkimedian.item.WarpcoreItem;
import net.mcreator.arkimedian.item.UraniumshardItem;
import net.mcreator.arkimedian.item.UnrefinedaluminiumscrapItem;
import net.mcreator.arkimedian.item.ThrusterItem;
import net.mcreator.arkimedian.item.SynriafleshItem;
import net.mcreator.arkimedian.item.StranoplesfruitItem;
import net.mcreator.arkimedian.item.StatorItem;
import net.mcreator.arkimedian.item.SpoolItem;
import net.mcreator.arkimedian.item.SpacesuitItem;
import net.mcreator.arkimedian.item.SpaceproofplatingItem;
import net.mcreator.arkimedian.item.SorosteellumpItem;
import net.mcreator.arkimedian.item.ShipcontrolunitItem;
import net.mcreator.arkimedian.item.RotorItem;
import net.mcreator.arkimedian.item.RefinedoilItem;
import net.mcreator.arkimedian.item.PressurechamberItem;
import net.mcreator.arkimedian.item.PlasticresinItem;
import net.mcreator.arkimedian.item.PlasticItem;
import net.mcreator.arkimedian.item.NaplaberryItem;
import net.mcreator.arkimedian.item.MotorItem;
import net.mcreator.arkimedian.item.ManufactureditemItem;
import net.mcreator.arkimedian.item.IronspoolemptyItem;
import net.mcreator.arkimedian.item.HolohraphiccoreunitItem;
import net.mcreator.arkimedian.item.HeavyplateItem;
import net.mcreator.arkimedian.item.HealgelItem;
import net.mcreator.arkimedian.item.GrelhoundFurItem;
import net.mcreator.arkimedian.item.GoldIronspoolItem;
import net.mcreator.arkimedian.item.FueltankItem;
import net.mcreator.arkimedian.item.FabricItem;
import net.mcreator.arkimedian.item.ExoskeletonchestplateItem;
import net.mcreator.arkimedian.item.ExoskeletonbootsItem;
import net.mcreator.arkimedian.item.ExoskeletonLeggingsItem;
import net.mcreator.arkimedian.item.EnergycoreItem;
import net.mcreator.arkimedian.item.EmptyPressurecoreItem;
import net.mcreator.arkimedian.item.DocreantileFleshItem;
import net.mcreator.arkimedian.item.CrudeoilItem;
import net.mcreator.arkimedian.item.CopperspoolItem;
import net.mcreator.arkimedian.item.CopperIronspoolItem;
import net.mcreator.arkimedian.item.ComputerItem;
import net.mcreator.arkimedian.item.ComplexcircuitItem;
import net.mcreator.arkimedian.item.ChainswordItem;
import net.mcreator.arkimedian.item.CeramitedustItem;
import net.mcreator.arkimedian.item.CarbondioxideItem;
import net.mcreator.arkimedian.item.CanisterItem;
import net.mcreator.arkimedian.item.CableItem;
import net.mcreator.arkimedian.item.BoltsItem;
import net.mcreator.arkimedian.item.BoltriteItem;
import net.mcreator.arkimedian.item.BoltgunItem;
import net.mcreator.arkimedian.item.BoltcontainerItem;
import net.mcreator.arkimedian.item.BiomassItem;
import net.mcreator.arkimedian.item.BauxiteItem;
import net.mcreator.arkimedian.item.ArkimedianAV1PowerarmorItem;
import net.mcreator.arkimedian.item.AmmoupgradeItem;
import net.mcreator.arkimedian.item.AluminiumsheetItem;
import net.mcreator.arkimedian.item.AluminiumacidItem;
import net.mcreator.arkimedian.item.AluminiumItem;
import net.mcreator.arkimedian.item.AirductfabricItem;
import net.mcreator.arkimedian.ArkimedianMod;

public class ArkimedianModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, ArkimedianMod.MODID);
	public static final RegistryObject<Item> INPUT = block(ArkimedianModBlocks.INPUT);
	public static final RegistryObject<Item> CONSTRUCTIONCORE = block(ArkimedianModBlocks.CONSTRUCTIONCORE);
	public static final RegistryObject<Item> ASAD = REGISTRY.register("asad", () -> new WrenchItem());
	public static final RegistryObject<Item> CIRCUITS = REGISTRY.register("circuits", () -> new ManufactureditemItem());
	public static final RegistryObject<Item> MOTOR = REGISTRY.register("motor", () -> new MotorItem());
	public static final RegistryObject<Item> SPOOL = REGISTRY.register("spool", () -> new SpoolItem());
	public static final RegistryObject<Item> COPPERSPOOL = REGISTRY.register("copperspool", () -> new CopperspoolItem());
	public static final RegistryObject<Item> CABLE = REGISTRY.register("cable", () -> new CableItem());
	public static final RegistryObject<Item> HEAVYPLATE = REGISTRY.register("heavyplate", () -> new HeavyplateItem());
	public static final RegistryObject<Item> STATOR = REGISTRY.register("stator", () -> new StatorItem());
	public static final RegistryObject<Item> ROTOR = REGISTRY.register("rotor", () -> new RotorItem());
	public static final RegistryObject<Item> SMELTERY = block(ArkimedianModBlocks.SMELTERY);
	public static final RegistryObject<Item> GASEXHAUST = block(ArkimedianModBlocks.GASEXHAUST);
	public static final RegistryObject<Item> CARBONDIOXIDE = REGISTRY.register("carbondioxide", () -> new CarbondioxideItem());
	public static final RegistryObject<Item> GWEN_SERVER = block(ArkimedianModBlocks.GWEN_SERVER);
	public static final RegistryObject<Item> COMPUTER = REGISTRY.register("computer", () -> new ComputerItem());
	public static final RegistryObject<Item> BELT_AV_I = block(ArkimedianModBlocks.BELT_AV_I);
	public static final RegistryObject<Item> OUTPUT = block(ArkimedianModBlocks.OUTPUT);
	public static final RegistryObject<Item> STORAGECONTAINER = block(ArkimedianModBlocks.STORAGECONTAINER);
	public static final RegistryObject<Item> REFINERY = block(ArkimedianModBlocks.REFINERY);
	public static final RegistryObject<Item> PLASTIC = REGISTRY.register("plastic", () -> new PlasticItem());
	public static final RegistryObject<Item> PLASTICRESIN = REGISTRY.register("plasticresin", () -> new PlasticresinItem());
	public static final RegistryObject<Item> CRUDEOIL = REGISTRY.register("crudeoil", () -> new CrudeoilItem());
	public static final RegistryObject<Item> REFINEDOIL = REGISTRY.register("refinedoil", () -> new RefinedoilItem());
	public static final RegistryObject<Item> OREVEINORE = block(ArkimedianModBlocks.OREVEINORE);
	public static final RegistryObject<Item> OREVEINBLOCK = block(ArkimedianModBlocks.OREVEINBLOCK);
	public static final RegistryObject<Item> OILVEIN = block(ArkimedianModBlocks.OILVEIN);
	public static final RegistryObject<Item> MINER = block(ArkimedianModBlocks.MINER);
	public static final RegistryObject<Item> ARKIMEDIAN_AV_1_POWERARMOR_HELMET = REGISTRY.register("arkimedian_av_1_powerarmor_helmet", () -> new ArkimedianAV1PowerarmorItem.Helmet());
	public static final RegistryObject<Item> ARKIMEDIAN_AV_1_POWERARMOR_CHESTPLATE = REGISTRY.register("arkimedian_av_1_powerarmor_chestplate", () -> new ArkimedianAV1PowerarmorItem.Chestplate());
	public static final RegistryObject<Item> ARKIMEDIAN_AV_1_POWERARMOR_LEGGINGS = REGISTRY.register("arkimedian_av_1_powerarmor_leggings", () -> new ArkimedianAV1PowerarmorItem.Leggings());
	public static final RegistryObject<Item> ARKIMEDIAN_AV_1_POWERARMOR_BOOTS = REGISTRY.register("arkimedian_av_1_powerarmor_boots", () -> new ArkimedianAV1PowerarmorItem.Boots());
	public static final RegistryObject<Item> FOUNDATION = block(ArkimedianModBlocks.FOUNDATION);
	public static final RegistryObject<Item> COPPERVEINORE = block(ArkimedianModBlocks.COPPERVEINORE);
	public static final RegistryObject<Item> COPPERVEINBLOCK = block(ArkimedianModBlocks.COPPERVEINBLOCK);
	public static final RegistryObject<Item> IRONSPOOLEMPTY = REGISTRY.register("ironspoolempty", () -> new IronspoolemptyItem());
	public static final RegistryObject<Item> COPPER_IRONSPOOL = REGISTRY.register("copper_ironspool", () -> new CopperIronspoolItem());
	public static final RegistryObject<Item> GOLD_IRONSPOOL = REGISTRY.register("gold_ironspool", () -> new GoldIronspoolItem());
	public static final RegistryObject<Item> MERGER = block(ArkimedianModBlocks.MERGER);
	public static final RegistryObject<Item> MINERSHAFT = block(ArkimedianModBlocks.MINERSHAFT);
	public static final RegistryObject<Item> COMPLEXCIRCUIT = REGISTRY.register("complexcircuit", () -> new ComplexcircuitItem());
	public static final RegistryObject<Item> OILRIG = block(ArkimedianModBlocks.OILRIG);
	public static final RegistryObject<Item> PIPE = block(ArkimedianModBlocks.PIPE);
	public static final RegistryObject<Item> EXOSKELETONCHESTPLATE = REGISTRY.register("exoskeletonchestplate", () -> new ExoskeletonchestplateItem());
	public static final RegistryObject<Item> EXOSKELETONBOOTS = REGISTRY.register("exoskeletonboots", () -> new ExoskeletonbootsItem());
	public static final RegistryObject<Item> EXOSKELETON_LEGGINGS = REGISTRY.register("exoskeleton_leggings", () -> new ExoskeletonLeggingsItem());
	public static final RegistryObject<Item> FABRIC = REGISTRY.register("fabric", () -> new FabricItem());
	public static final RegistryObject<Item> PIPEOUTPUT = block(ArkimedianModBlocks.PIPEOUTPUT);
	public static final RegistryObject<Item> FLUIDINPUT = block(ArkimedianModBlocks.FLUIDINPUT);
	public static final RegistryObject<Item> SPLITTER = block(ArkimedianModBlocks.SPLITTER);
	public static final RegistryObject<Item> MARSSTONE = block(ArkimedianModBlocks.MARSSTONE);
	public static final RegistryObject<Item> MARSSAND = block(ArkimedianModBlocks.MARSSAND);
	public static final RegistryObject<Item> MARSGOLDOREVEIN = block(ArkimedianModBlocks.MARSGOLDOREVEIN);
	public static final RegistryObject<Item> SPACESUIT_HELMET = REGISTRY.register("spacesuit_helmet", () -> new SpacesuitItem.Helmet());
	public static final RegistryObject<Item> THRUSTER = REGISTRY.register("thruster", () -> new ThrusterItem());
	public static final RegistryObject<Item> SPACEPROOFPLATING = REGISTRY.register("spaceproofplating", () -> new SpaceproofplatingItem());
	public static final RegistryObject<Item> ENERGYCORE = REGISTRY.register("energycore", () -> new EnergycoreItem());
	public static final RegistryObject<Item> AIRDUCTFABRIC = REGISTRY.register("airductfabric", () -> new AirductfabricItem());
	public static final RegistryObject<Item> FUELTANK = REGISTRY.register("fueltank", () -> new FueltankItem());
	public static final RegistryObject<Item> SHIPCONTROLUNIT = REGISTRY.register("shipcontrolunit", () -> new ShipcontrolunitItem());
	public static final RegistryObject<Item> ALUMINIUMORE_VEIN = block(ArkimedianModBlocks.ALUMINIUMORE_VEIN);
	public static final RegistryObject<Item> ALUMINIUMOREVEINSIDE = block(ArkimedianModBlocks.ALUMINIUMOREVEINSIDE);
	public static final RegistryObject<Item> BAUXITE = REGISTRY.register("bauxite", () -> new BauxiteItem());
	public static final RegistryObject<Item> ALUMINIUM = REGISTRY.register("aluminium", () -> new AluminiumItem());
	public static final RegistryObject<Item> UNREFINEDALUMINIUMSCRAP = REGISTRY.register("unrefinedaluminiumscrap", () -> new UnrefinedaluminiumscrapItem());
	public static final RegistryObject<Item> ALUMINIUMACID = REGISTRY.register("aluminiumacid", () -> new AluminiumacidItem());
	public static final RegistryObject<Item> ELECTROLYZER = block(ArkimedianModBlocks.ELECTROLYZER);
	public static final RegistryObject<Item> NTRASYL_WOOD = block(ArkimedianModBlocks.NTRASYL_WOOD);
	public static final RegistryObject<Item> NTRASYL_LOG = block(ArkimedianModBlocks.NTRASYL_LOG);
	public static final RegistryObject<Item> NTRASYL_LEAVES = block(ArkimedianModBlocks.NTRASYL_LEAVES);
	public static final RegistryObject<Item> NTRASYLLEAVESSLAB = block(ArkimedianModBlocks.NTRASYLLEAVESSLAB);
	public static final RegistryObject<Item> BOLTGUN = REGISTRY.register("boltgun", () -> new BoltgunItem());
	public static final RegistryObject<Item> CHAINSWORD = REGISTRY.register("chainsword", () -> new ChainswordItem());
	public static final RegistryObject<Item> SININCA_WOOD = block(ArkimedianModBlocks.SININCA_WOOD);
	public static final RegistryObject<Item> SININCA_LOG = block(ArkimedianModBlocks.SININCA_LOG);
	public static final RegistryObject<Item> SININCA_LEAVES = block(ArkimedianModBlocks.SININCA_LEAVES);
	public static final RegistryObject<Item> SYNRIA_SPAWN_EGG = REGISTRY.register("synria_spawn_egg", () -> new ForgeSpawnEggItem(ArkimedianModEntities.SYNRIA, -16738048, -16751104, new Item.Properties()));
	public static final RegistryObject<Item> SPACEASSEMBLER = block(ArkimedianModBlocks.SPACEASSEMBLER);
	public static final RegistryObject<Item> BELT_AV_II = block(ArkimedianModBlocks.BELT_AV_II);
	public static final RegistryObject<Item> ALUMINIUMSHEET = REGISTRY.register("aluminiumsheet", () -> new AluminiumsheetItem());
	public static final RegistryObject<Item> DISPLAY = block(ArkimedianModBlocks.DISPLAY);
	public static final RegistryObject<Item> ENERGYCLUSTER = block(ArkimedianModBlocks.ENERGYCLUSTER);
	public static final RegistryObject<Item> EMPTY_PRESSURECORE = REGISTRY.register("empty_pressurecore", () -> new EmptyPressurecoreItem());
	public static final RegistryObject<Item> CUTIE_SPAWN_EGG = REGISTRY.register("cutie_spawn_egg", () -> new ForgeSpawnEggItem(ArkimedianModEntities.CUTIE, -16737844, -16750951, new Item.Properties()));
	public static final RegistryObject<Item> CERAMITEVEIN = block(ArkimedianModBlocks.CERAMITEVEIN);
	public static final RegistryObject<Item> CERAMITEDUST = REGISTRY.register("ceramitedust", () -> new CeramitedustItem());
	public static final RegistryObject<Item> CERAMITE = block(ArkimedianModBlocks.CERAMITE);
	public static final RegistryObject<Item> CERACRETE = block(ArkimedianModBlocks.CERACRETE);
	public static final RegistryObject<Item> CERACRETE_SLAB = block(ArkimedianModBlocks.CERACRETE_SLAB);
	public static final RegistryObject<Item> CERACRETE_STAIR = block(ArkimedianModBlocks.CERACRETE_STAIR);
	public static final RegistryObject<Item> CERACRETE_WALL = block(ArkimedianModBlocks.CERACRETE_WALL);
	public static final RegistryObject<Item> METALCASING = block(ArkimedianModBlocks.METALCASING);
	public static final RegistryObject<Item> METALCASING_STAIRS = block(ArkimedianModBlocks.METALCASING_STAIRS);
	public static final RegistryObject<Item> METALCASING_SLAB = block(ArkimedianModBlocks.METALCASING_SLAB);
	public static final RegistryObject<Item> NAPLABERRY = REGISTRY.register("naplaberry", () -> new NaplaberryItem());
	public static final RegistryObject<Item> NAPLA = block(ArkimedianModBlocks.NAPLA);
	public static final RegistryObject<Item> STRANOPLESFRUIT = REGISTRY.register("stranoplesfruit", () -> new StranoplesfruitItem());
	public static final RegistryObject<Item> EXTRATERRESTRICDIRT = block(ArkimedianModBlocks.EXTRATERRESTRICDIRT);
	public static final RegistryObject<Item> EXTRATERRESTICGRASS = block(ArkimedianModBlocks.EXTRATERRESTICGRASS);
	public static final RegistryObject<Item> BIOMASS = REGISTRY.register("biomass", () -> new BiomassItem());
	public static final RegistryObject<Item> SILANITE = block(ArkimedianModBlocks.SILANITE);
	public static final RegistryObject<Item> TURNITE = block(ArkimedianModBlocks.TURNITE);
	public static final RegistryObject<Item> CALITE = block(ArkimedianModBlocks.CALITE);
	public static final RegistryObject<Item> BELTLIFTINPUT = block(ArkimedianModBlocks.BELTLIFTINPUT);
	public static final RegistryObject<Item> BELTLIFTOUTPUT = block(ArkimedianModBlocks.BELTLIFTOUTPUT);
	public static final RegistryObject<Item> BELTLIFT = block(ArkimedianModBlocks.BELTLIFT);
	public static final RegistryObject<Item> ERNETMONSTROCITY_SPAWN_EGG = REGISTRY.register("ernetmonstrocity_spawn_egg", () -> new ForgeSpawnEggItem(ArkimedianModEntities.ERNETMONSTROCITY, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> SYNRIAFLESH = REGISTRY.register("synriaflesh", () -> new SynriafleshItem());
	public static final RegistryObject<Item> CANISTER = REGISTRY.register("canister", () -> new CanisterItem());
	public static final RegistryObject<Item> BIOMASSWOOD_PLANKS = block(ArkimedianModBlocks.BIOMASSWOOD_PLANKS);
	public static final RegistryObject<Item> BIOMASSWOOD_STAIRS = block(ArkimedianModBlocks.BIOMASSWOOD_STAIRS);
	public static final RegistryObject<Item> BIOMASSWOOD_SLAB = block(ArkimedianModBlocks.BIOMASSWOOD_SLAB);
	public static final RegistryObject<Item> BIOMASSWOOD_FENCE = block(ArkimedianModBlocks.BIOMASSWOOD_FENCE);
	public static final RegistryObject<Item> PLATECASING = block(ArkimedianModBlocks.PLATECASING);
	public static final RegistryObject<Item> PLATECASING_STAIRS = block(ArkimedianModBlocks.PLATECASING_STAIRS);
	public static final RegistryObject<Item> PLATECASING_SLAB = block(ArkimedianModBlocks.PLATECASING_SLAB);
	public static final RegistryObject<Item> EXTRATERRESTRICMUD = block(ArkimedianModBlocks.EXTRATERRESTRICMUD);
	public static final RegistryObject<Item> XENOSHROOMSTEM = block(ArkimedianModBlocks.XENOSHROOMSTEM);
	public static final RegistryObject<Item> XENOSHROOMHAT = block(ArkimedianModBlocks.XENOSHROOMHAT);
	public static final RegistryObject<Item> TORANILE_WOOD = block(ArkimedianModBlocks.TORANILE_WOOD);
	public static final RegistryObject<Item> TORANILE_LOG = block(ArkimedianModBlocks.TORANILE_LOG);
	public static final RegistryObject<Item> TORANILE_LEAVES = block(ArkimedianModBlocks.TORANILE_LEAVES);
	public static final RegistryObject<Item> XENTANIVESNEST = block(ArkimedianModBlocks.XENTANIVESNEST);
	public static final RegistryObject<Item> XENTANIVE_SPAWN_EGG = REGISTRY.register("xentanive_spawn_egg", () -> new ForgeSpawnEggItem(ArkimedianModEntities.XENTANIVE, -9545960, -13294576, new Item.Properties()));
	public static final RegistryObject<Item> FILLEDXENTANIVESNEST = block(ArkimedianModBlocks.FILLEDXENTANIVESNEST);
	public static final RegistryObject<Item> HEALGEL = REGISTRY.register("healgel", () -> new HealgelItem());
	public static final RegistryObject<Item> GRELHOUND_SPAWN_EGG = REGISTRY.register("grelhound_spawn_egg", () -> new ForgeSpawnEggItem(ArkimedianModEntities.GRELHOUND, -13421773, -12763843, new Item.Properties()));
	public static final RegistryObject<Item> BIOMASSGENERATOR = block(ArkimedianModBlocks.BIOMASSGENERATOR);
	public static final RegistryObject<Item> DOCREANITILE_SPAWN_EGG = REGISTRY.register("docreanitile_spawn_egg", () -> new ForgeSpawnEggItem(ArkimedianModEntities.DOCREANITILE, -6724096, -10079488, new Item.Properties()));
	public static final RegistryObject<Item> DOCREANITILEFLESH = block(ArkimedianModBlocks.DOCREANITILEFLESH);
	public static final RegistryObject<Item> DOCREANTILE_FLESH = REGISTRY.register("docreantile_flesh", () -> new DocreantileFleshItem());
	public static final RegistryObject<Item> GRELHOUND_FUR = REGISTRY.register("grelhound_fur", () -> new GrelhoundFurItem());
	public static final RegistryObject<Item> GVRAL_SPAWN_EGG = REGISTRY.register("gvral_spawn_egg", () -> new ForgeSpawnEggItem(ArkimedianModEntities.GVRAL, -10066330, -3355444, new Item.Properties()));
	public static final RegistryObject<Item> SICARIONFIGHTER_SPAWN_EGG = REGISTRY.register("sicarionfighter_spawn_egg", () -> new ForgeSpawnEggItem(ArkimedianModEntities.SICARIONFIGHTER, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> EXHAUSTWITHWIRECONNECT = block(ArkimedianModBlocks.EXHAUSTWITHWIRECONNECT);
	public static final RegistryObject<Item> MENTRIOLITE = block(ArkimedianModBlocks.MENTRIOLITE);
	public static final RegistryObject<Item> MENTRIOLITEWARP = block(ArkimedianModBlocks.MENTRIOLITEWARP);
	public static final RegistryObject<Item> WARPCRYSTAL = block(ArkimedianModBlocks.WARPCRYSTAL);
	public static final RegistryObject<Item> WARPCORE = REGISTRY.register("warpcore", () -> new WarpcoreItem());
	public static final RegistryObject<Item> PRESSURECHAMBER = REGISTRY.register("pressurechamber", () -> new PressurechamberItem());
	public static final RegistryObject<Item> HOLOGRAMDISPLAYER = block(ArkimedianModBlocks.HOLOGRAMDISPLAYER);
	public static final RegistryObject<Item> GVRALHOLOGRAM = block(ArkimedianModBlocks.GVRALHOLOGRAM);
	public static final RegistryObject<Item> HOLOHRAPHICCOREUNIT = REGISTRY.register("holohraphiccoreunit", () -> new HolohraphiccoreunitItem());
	public static final RegistryObject<Item> UNRINRIL_LOG = block(ArkimedianModBlocks.UNRINRIL_LOG);
	public static final RegistryObject<Item> UNRINRIL_WOOD = block(ArkimedianModBlocks.UNRINRIL_WOOD);
	public static final RegistryObject<Item> HEATEDDIRT = block(ArkimedianModBlocks.HEATEDDIRT);
	public static final RegistryObject<Item> HEATEDGRASSBLOCK = block(ArkimedianModBlocks.HEATEDGRASSBLOCK);
	public static final RegistryObject<Item> GNIRILION_SPAWN_EGG = REGISTRY.register("gnirilion_spawn_egg", () -> new ForgeSpawnEggItem(ArkimedianModEntities.GNIRILION, -11849178, -12964829, new Item.Properties()));
	public static final RegistryObject<Item> CRILNAZITE = block(ArkimedianModBlocks.CRILNAZITE);
	public static final RegistryObject<Item> MOSSY_CRILNAZITE = block(ArkimedianModBlocks.MOSSY_CRILNAZITE);
	public static final RegistryObject<Item> SOROSTEELLUMP = REGISTRY.register("sorosteellump", () -> new SorosteellumpItem());
	public static final RegistryObject<Item> BOLTRITE = REGISTRY.register("boltrite", () -> new BoltriteItem());
	public static final RegistryObject<Item> BOLTS = REGISTRY.register("bolts", () -> new BoltsItem());
	public static final RegistryObject<Item> BOLTCONTAINER = REGISTRY.register("boltcontainer", () -> new BoltcontainerItem());
	public static final RegistryObject<Item> URANIUMSHARD = REGISTRY.register("uraniumshard", () -> new UraniumshardItem());
	public static final RegistryObject<Item> AMMOUPGRADE = REGISTRY.register("ammoupgrade", () -> new AmmoupgradeItem());
	public static final RegistryObject<Item> WIRINGBLOCK = block(ArkimedianModBlocks.WIRINGBLOCK);

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
